name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Dependabot Auto-Merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "dependencies"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Auto-merged Dependabot PR"
          MERGE_FILTER_AUTHOR: "dependabot[bot]"
